services:
  disney-tips:
    image: nginx:alpine
    container_name: disney-tips
    restart: unless-stopped
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.disney-tips.rule=Host(`disney.bound.tips`)"
      - "traefik.http.routers.disney-tips.entrypoints=http"
      - "traefik.http.services.disney-tips.loadbalancer.server.port=80"
    networks:
      - traefik

networks:
  traefik:
    external: true
